const PRONUNCIATION_FIX = {
  // 公司/商业_FIX
  Ltd: 'limited',
  Inc: 'incorporated',
  Corp: 'corporation',
  Co: 'company',

  // 称谓
  Mr: 'mister',
  Mrs: 'missus',
  Ms: 'miz',
  Dr: 'doctor',
  Prof: 'professor',
  Jr: 'junior',
  Sr: 'senior',
  Rev: 'reverend',
  Gen: 'general',
  Col: 'colonel',
  Capt: 'captain',
  Sgt: 'sergeant',
  Lt: 'lieutenant',

  // 度量单位
  lb: 'pound',
  lbs: 'pounds',
  oz: 'ounce',
  ft: 'feet',
  yd: 'yard',
  mi: 'mile',
  kg: 'kilogram',
  mg: 'milligram',
  ml: 'milliliter',
  cm: 'centimeter',
  km: 'kilometer',

  // 地址
  St: 'street',
  Ave: 'avenue',
  Blvd: 'boulevard',
  Rd: 'road',
  Ln: 'lane',
  Ct: 'court',
  Apt: 'apartment',
  Ste: 'suite',

  // 时间
  Jan: 'january',
  Feb: 'february',
  Mar: 'march',
  Apr: 'april',
  Jun: 'june',
  Jul: 'july',
  Aug: 'august',
  Sep: 'september',
  Sept: 'september',
  Oct: 'october',
  Nov: 'november',
  Dec: 'december',
  Mon: 'monday',
  Tue: 'tuesday',
  Tues: 'tuesday',
  Wed: 'wednesday',
  Thu: 'thursday',
  Thurs: 'thursday',
  Fri: 'friday',
  Sat: 'saturday',
  Sun: 'sunday',

  // 其他常用
  etc: 'etcetera',
  vs: 'versus',
  govt: 'government',
  dept: 'department',
  approx: 'approximately',
  info: 'information',
  admin: 'administrator',
  mgmt: 'management',
  qty: 'quantity',
  amt: 'amount',
  acct: 'account',
  attn: 'attention',
  misc: 'miscellaneous',
  max: 'maximum',
  min: 'minimum',
  avg: 'average',
  est: 'established',
  intl: 'international',
  temp: 'temporary',
  ref: 'reference',
  vol: 'volume',
  No: 'number',
  Fig: 'figure',

  // 特殊，浏览器 API 不能支持发音的单词集合
  mhm: null,
};

export const PRONUNCIATION_FIX_MAP = new Map(Object.entries(PRONUNCIATION_FIX));
